name: Run tests with Tox

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-inclusive-naming-check:
    name: Inclusive naming
    uses: canonical/inclusive-naming/.github/workflows/woke.yaml@main
    with:
      fail-on-error: "true"

  validate-wheelhouse:
    name: Validate Wheelhouse
    uses: charmed-kubernetes/workflows/.github/workflows/validate-wheelhouse.yaml@main
    with:
      python: "['3.10', '3.12']"

  lint-unit:
    name: Lint Unit
    uses: charmed-kubernetes/workflows/.github/workflows/lint-unit.yaml@main
    with:
      python: "['3.10', '3.12']"

  resources-build:
    name: Build Resources with docker
    runs-on: ubuntu-22.04
    needs:
      - lint-unit
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build Resources
        run:  sudo ./build-flannel-resources.sh
      - name: Upload resource artifact
        uses: actions/upload-artifact@v4
        with:
          name: flannel-resources
          path: ./flannel*.tar.gz

  integration-tests:
    name: Integration test with LXD
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    needs:
      - resources-build
      - lint-unit
      - validate-wheelhouse
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Read charmcraft version file
        id: charmcraft
        run: echo "channel=$(cat .charmcraft-channel)" >> $GITHUB_OUTPUT

      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
          juju-channel: 3/stable
          charmcraft-channel: ${{ steps.charmcraft.outputs.channel }}
          bootstrap-constraints: "arch=amd64 cores=2 mem=4G"

      - name: Download resource artifacts
        uses: actions/download-artifact@v4
        with:
          name: flannel-resources

      - name: Run integration test
        run: tox -e integration

      - name: Setup Debug Artifact Collection
        if: failure()
        run: mkdir tmp

      - name: Collect Juju Logs
        if: failure()
        run: juju debug-log --replay --no-tail | tee tmp/juju-status.txt

      - name: Upload debug artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-run-artifacts
          path: tmp
