name: Run tests with Tox

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-inclusive-naming-check:
    name: Inclusive naming
    uses: canonical-web-and-design/Inclusive-naming/.github/workflows/woke.yaml@main
    with:
      fail-on-error: "true"

  validate-wheelhouse:
    name: Validate Wheelhouse
    uses: charmed-kubernetes/workflows/.github/workflows/validate-wheelhouse.yaml@main

  lint-unit:
    name: Lint Unit
    uses: charmed-kubernetes/workflows/.github/workflows/lint-unit.yaml@main

  integration-tests:
    name: Integration test with Vsphere
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: vsphere
          credentials-yaml: ${{ secrets.CREDENTIALS_YAML }}
          clouds-yaml: ${{ secrets.CLOUDS_YAML }}
          bootstrap-options: "${{ secrets.FOCAL_BOOTSTRAP_OPTIONS }} --model-default datastore=vsanDatastore --model-default primary-network=VLAN_2764"
          bootstrap-constraints: "arch=amd64 cores=2 mem=4G"

      - name: Run integration test
        run: tox -e integration

      - name: Setup Debug Artifact Collection
        if: failure()
        run: mkdir tmp

      - name: Collect Juju Logs
        if: failure()
        run: juju debug-log --replay --no-tail | tee tmp/juju-status.txt

      - name: Upload debug artifacts
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-run-artifacts
          path: tmp